import React from 'react';
import type { ServiceRequest } from '../types/booking';

interface CustomerExportPDFProps {
  requests: ServiceRequest[];
  exportId: string;
}

export const CustomerExportPDF = React.forwardRef<HTMLDivElement, CustomerExportPDFProps>(
  ({ requests, exportId }, ref) => {
    
    const exportDate = new Date().toLocaleDateString('en-AE', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
    const exportTime = new Date().toLocaleTimeString('en-AE');

    return (
      <div className="hidden">
        <div 
          ref={ref} 
          className="bg-white w-[210mm] min-h-[297mm] p-[15mm] mx-auto box-border font-sans text-[12px] text-gray-800"
          style={{ WebkitPrintColorAdjust: 'exact', colorAdjust: 'exact' }}
        >
          {/* Header */}
          <div className="flex justify-between items-center border-b-2 border-[#1C2C54] pb-4 mb-6">
            <div>
              <h1 className="text-2xl font-bold text-[#1C2C54] uppercase tracking-wide mb-1">
                RID OUT PEST CONTROL SERVICES
              </h1>
              <p className="text-[#1C2C54] text-sm">Pest Control & Fumigation Solutions</p>
              <p className="text-gray-500 text-xs mt-1">Dubai | Sharjah | Ajman</p>
              <p className="text-gray-500 text-xs">Phone: +971 55 4720124</p>
            </div>
            <div>
               {/* Using text instead of logo to avoid massive base64 conversion delays if logo fails, but we can use logo.png */}
               <img src="/logo-black.png" alt="Rid Out Pest Control" className="h-16 w-auto object-contain" />
            </div>
          </div>

          {/* Export Meta Info */}
          <div className="bg-gray-100 p-4 rounded-md mb-8">
            <h2 className="text-lg font-bold text-[#1C2C54] mb-2 uppercase border-b border-gray-300 pb-1">Customer Data Export Archive</h2>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <p><span className="font-bold">Export ID:</span> {exportId}</p>
              <p><span className="font-bold">Export Date:</span> {exportDate}</p>
              <p><span className="font-bold">Export Time:</span> {exportTime}</p>
              <p><span className="font-bold">Total Records:</span> {requests.length}</p>
              <p><span className="font-bold">Initiated By:</span> Administrator</p>
            </div>
          </div>

          {/* Customer Records List */}
          <div className="space-y-6">
            {requests.map((req, index) => (
              <div key={req.id} className="border border-gray-300 rounded-md p-4 break-inside-avoid">
                <div className="flex justify-between items-center bg-[#1C2C54] text-white p-2 -mx-4 -mt-4 mb-3 rounded-t-md">
                  <h3 className="font-bold">Record #{index + 1}: {req.customer_name}</h3>
                  <span className="text-xs">{req.request_number}</span>
                </div>
                
                <div className="grid grid-cols-2 gap-x-6 gap-y-2 text-xs">
                  <div>
                    <p className="text-gray-500 uppercase text-[10px] font-bold">Contact Details</p>
                    <p><span className="font-semibold">Phone:</span> {req.mobile}</p>
                    <p><span className="font-semibold">Email:</span> {req.email || 'N/A'}</p>
                    <p><span className="font-semibold">Location:</span> {req.location}</p>
                    <p><span className="font-semibold">Property:</span> {req.property_type}</p>
                  </div>
                  <div>
                    <p className="text-gray-500 uppercase text-[10px] font-bold">Service Details</p>
                    <p><span className="font-semibold">Service:</span> {Array.isArray(req.service_name) ? req.service_name.join(', ') : req.service_name}</p>
                    <p><span className="font-semibold">Date Requested:</span> {req.preferred_date} at {req.preferred_time}</p>
                    <p><span className="font-semibold">Status:</span> {req.status}</p>
                    <p><span className="font-semibold">Created:</span> {new Date(req.created_at).toLocaleString('en-AE')}</p>
                  </div>
                  <div className="col-span-2 mt-2 pt-2 border-t border-gray-100">
                     <p><span className="font-semibold">Customer Notes:</span> {req.notes || 'None'}</p>
                     <p><span className="font-semibold">Internal Notes:</span> {req.internal_notes || 'None'}</p>
                     {req.is_urgent && <p className="text-red-600 font-bold mt-1">⚠️ Marked as Urgent</p>}
                  </div>
                </div>
              </div>
            ))}
          </div>
          
          {/* Footer Footer */}
          <div className="mt-8 pt-4 border-t border-gray-300 text-center text-[10px] text-gray-400">
            Page 1 / Generated by Rid Out Pest Control Admin System
          </div>
        </div>
      </div>
    );
  }
);

CustomerExportPDF.displayName = 'CustomerExportPDF';
